VIA_ENABLE = yes
VIAL_ENABLE = yes
VIAL_INSECURE = yes

OLED_ENABLE = yes
MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
RGBLIGHT_ENABLE = yes
RGB_MATRIX_ENABLE = no

SRC += sly_oled.c

COMBO_ENABLE = no
TAP_DANCE_ENABLE = no
KEY_OVERRIDE_ENABLE = no

VIAL_COMBO_ENABLE = no
VIAL_TAP_DANCE_ENABLE = no
VIAL_KEY_OVERRIDE_ENABLE = no

QMK_SETTINGS = no